### ISSUE TITLE
Background image is not setting up with Background Image URL option

### ISSUE THREAD

**Issue by jogendra** [PJijin/Cover-Image-Generator#14]
Hi @PJijin 👋 
Thanks for creating this awesome tool. I come across this on dev.to and love using it for generating cover for my blogs.

**Describe the bug**
When I paste image URL into **Background Image URL** field, it gets reflected to design are but when I download that cover, that image is not there.

**To Reproduce**
1. Create a new cover
2. Paste an image URL into **Background Image URL** field
3. Download the cover

**Expected behavior**
The image applied from the URL should be there in cover.

**Screenshots**

During editing:

![Screenshot 2020-07-28 at 16 08 39](https://user-images.githubusercontent.com/20956124/88655610-9cd0a480-d0ec-11ea-8bbe-350103775f92.png)

The image URL I am trying is: https://user-images.githubusercontent.com/20956124/88571617-90503b80-d05b-11ea-9d57-e21714f66636.png

After Downloading:

![CoverImage](https://user-images.githubusercontent.com/20956124/88655703-bffb5400-d0ec-11ea-8724-8a1517118f94.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.0 (Big Sur Beta)
 - Browser: Firefox (78.0.2)

**Comment by PJijin** [comment]
Hey👋🏻  

The issue is related to the CORS in the image URL. I have fixed the issue now. You can clear cache (CMD + Shift + R) and check now. 

Thank you 😀

**Comment by jogendra** [comment]
Thank you @PJijin! That was quick  ✨ 🚀
