### ISSUE TITLE
"Only a max of 250 modules is allowed in a sandbox"

### ISSUE THREAD

**Issue by djD-REK** [PJijin/Cover-Image-Generator#2]
**Describe the bug**
I got an error when I opened this project in CodeSandbox to try to make a live demo there.

**To Reproduce**
1. Go to codesandbox.io
2. Click on Create Sandbox
3. Click on import
4. Enter the git url https://github.com/PJijin/Cover-Image-Generator.git
5. Click import
6. See error

**Expected behavior**
Not sure what the error means

**Additional context**
You can try the direct URL to see the error https://codesandbox.io/s/github/PJijin/Cover-Image-Generator

**Comment by PJijin** [comment]
If you want to try it out online you can use https://glitch.com/

Project Link: https://glitch.com/~pjijin-cover-image-generator

CodeSandBox limits modules to 250.
