### ISSUE TITLE
PNG files are JPEG with ".png" extension

### ISSUE THREAD

**Issue by sfeuga** [PJijin/Cover-Image-Generator#3]
**Describe the bug**

**To Reproduce**
1. Go to https://cover-image-generator.pjijin1.now.sh/
2. Select `PNG` under Properties => Format
2. Click on `Download Image`
3. Read meta data of the downloaded file from `cli` (with `ImageMagick` package) and `Gimp`

**Expected behavior**

**Screenshots**
1. __cli__: `$ identify -verbose screenshot.png` give
     - `Format: JPEG (Joint Photographic Experts Group JFIF format)`
     - `Mime type: image/jpeg`
2. __Gimp__: ![Screenshot](https://raw.githubusercontent.com/sfeuga/sfeuga.github.io/13543c4e334df1e78061303ac132c7aadfdd436f/imgs/Screenshot%20from%202019-08-15%2015-01-29.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux Fedora 30
 - Browser Google Chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by PJijin** [comment]
Fixed 😃
