### ISSUE TITLE
[Online App]: Impossible to download file

### ISSUE THREAD

**Issue by sfeuga** [PJijin/Cover-Image-Generator#4]
**Describe the bug**

**To Reproduce**
1. Go to https://cover-image-generator.pjijin1.now.sh/
2. Click on `Download Image`

**Expected behavior**
A file is downloaded but nothing happen

**Desktop (please complete the following information):**
 - OS: GNU/Linux Fedora 30
 - Browser Firefox
 - Version 68.0 (64-bit)

**Additional context**
Tested OK on the same OS with Google Chrome 76.0.3809.100 (Official Build) (64-bit)

**Comment by sfeuga** [comment]
Quick question, is this Merge PR automatically deploy a new online version ?

**Comment by PJijin** [comment]
Clear cache and check demo. On mac CMD + Shift + R, On Windows Ctrl + F5
😀

**Comment by JP1016** [comment]
> Quick question, is this Merge PR automatically deploy a new online version ?
> Answer by myself: I think not, I did not noticed a CI file in your repo ;)

@sfeuga zeit now takes care of deploying, it deploys the PR branch as well as master branch whenever a changes is pushed to the branch

**Comment by sfeuga** [comment]
> Clear cache and check demo. On mac CMD + Shift + R, On Windows Ctrl + F5
> grinning

Damned ! I feel like a noob :laughing:

**Comment by JP1016** [comment]
@sfeuga its serverless deployment, just add a now.json file to your project and attach the project with githook, it automatically takes care of deployment
check the now.json file in this project.

**Comment by sfeuga** [comment]
Thx ! I did not know that, I will try on my next project.
Indeed, very cool app :smile_cat:
